### ISSUE TITLE
make available on maven central

### ISSUE THREAD

**Issue by WolfgangFahl** [aesteve/vertx-sse#18]
it would be great to be able to integrate this into a maven project by simply adding a dependency.

**Comment by aesteve** [comment]
Hello and thanks for your interest.

The goal is to integrate SSE into vertx-web, directly, instead of using a 3rd party library.

You can find the whole discussion [here](https://github.com/reactiverse/reactiverse/issues/5).

Unfortunately I'm missing time to work on such an implementation, but if by any chance I have some, I'll probably favor the vertx-web integration rather than publishing this module to Central.

Thank you.
